volumes:
  qemu:

services:
  qemu:
    image: qemux/qemu
    container_name: qemu
    environment:
      BOOT: "https://archive.org/download/linuxmint-22.1-xfce-64bit_202502/linuxmint-22.1-xfce-64bit.iso"
      RAM_SIZE: "4G"
      CPU_CORES: "2"
      DISK_SIZE: "32G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - "8006:8006"
      - "3389:3389/tcp"
      - "3389:3389/udp"
    volumes:
      - ./qemu:/storage

